name: conformity

channels:
  - defaults

dependencies:
  - python=3
  - ipython
  - anaconda
  - astropy
  - h5py
  - numpy
  - pandas
  - scipy
  - seaborn
  - pip
  - pip:
    - GitPython
    - progressbar2
    - halotools
    - Corrfunc
    - Sphinx
    - coverage
    - flake8
    - python-dotenv>=0.5.1
    - awscli
    - click
    - sphinx_rtd_theme
    - tqdm
    - cosmo-utils>=0.1.57
    - tables
    - progressbar2
    - cosmo-pair-counting
